### ISSUE TITLE
A Few Issues from the Last Few Months of Testing

### ISSUE THREAD

**Issue by jonch070** [gwatcha/reaper-keys#71] opened 2024-07-23 03:42 UTC
Hey hey!! Thanks for all the work on this. I've been seriously working with reaper keys as a film composer for a few months and am trying to make it my daily driver. I've been discovering a few issues so I thought I would put them in one issue. Let me know if there is a better way/if you would like separate issues for all of these 

- OpenInMidiEditor does not focus on midi editor when open and instead tries to rename current track. Cannot figure out why this is the case, previous commits did not have this problem
- Midi note movement horizontally not working, seems like there isn't focusing on midi note editor
- Help file does not focus search bar when open (QOL)
- In readme it says 0 = get to item start, but it is actually jump to start of project
- Visual timeline mode behaviour not starting from cursor when engaged (AntoineBalaine has a fix in his fork's state.lua that has worked for me)

Thank you!

**Comment by myrrc** [comment] 2024-07-23 23:15
Hi and thanks for reporting. 1 is fixed and I'm working on a test currently, as for other issues, I'll have a look

**Comment by myrrc** [comment] 2024-08-03 17:43
> - Help file does not focus search bar when open (QOL)
I didn't manage to reproduce the issue with binding window search bar. Can you record
a screencast showing that it doesn't focus?

**Comment by jonch070** [comment] 2024-08-11 16:31
of course! you can see here that if i start typing when i bring up the binding window I still am triggering reaper keys commands in the arrange until i click into it
![binding list issue](https://github.com/user-attachments/assets/d63bff08-6652-4e1e-bbae-e95d5325bb29)

**Comment by myrrc** [comment] 2024-10-27 13:00
Seems to be fixed in recent release, feel free to reopen if found again

**Closed by myrrc** 2024-10-27 13:00 UTC
