### ISSUE TITLE
weird behavior after exiting `rename track focus` WITH keypress (enter/esc) NOT click outside

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#35] opened 2020-07-06 08:07 UTC
Hey guys hows it going,

I have noticed weird behavior after exiting rename track focus WITH keypress (enter/esc) NOT click outside. If I enter the input field and then exit by pressing ent/esc.
Am I only experiencing this?
It seems something breaks in latest version of Reaper. The behavior goes back to normal when restarting Reaper
or switching project tab. I am not sure exactly what happens but this is what I can see:

1. many commands stop working
2. the action top bar menu item flashes for every keypress.

Problem persists in both master b5208a5 and dev f103f62 branch.
I'm not entirely sure if this is a reaper bug?
I'll get back w more info if I find something.

OS X 64-bit
REAPER v6.12c

**Comment by elgiovanno** [comment] 2020-07-06 20:21
Hey! So you're doing "<SPC>, t, r" to rename the track and when you enter or escape out of the field is when the issue shows up? If that is the case, it is not causing the issue on my end on osx REAPER 6.11.

**Comment by molleweide** [comment] 2020-07-07 07:19
Yeah but it also happens if double click the name field and press ent/esc to exit renaming.
Luckilly it goes away when swiching tabs so I can still use it!
I don't know how to go back to previous version of reaper to see if it is a problem with v6.12

**Comment by molleweide** [comment] 2020-07-08 09:02
One more thing:
If you generate the error/bug and then change name and exit by clicking outside >> then the bug goes away.
i.e. exit by click rectifies the problem it seems.

please say if you don't understand...

**Comment by gwatcha** [comment] 2020-07-08 23:49
Can't reproduce on Linux REAPER 6.12

**Comment by molleweide** [comment] 2020-07-12 12:28
Allright, I’ll get backbif I solve it! I’ve installed a lot of scripts lately so maybe that’s why.

**Comment by elgiovanno** [comment] 2020-07-18 15:11
I was able to duplicate this issue in 6.12c. i will dive deeper to see if I can find out what's going on. I have 6.11 running on the same system usinng the same reaper resource path with no issues.

**Comment by elgiovanno** [comment] 2020-07-18 15:18
It would be useful to know if this happens on windows. If not, could it be safe to deduce that the MacOS specific updates included in 6.12c are the culprit? Here's a screenshot of those updates. One of them is reascript related. ![Screenshot_20200718-111510.jpg](https://user-images.githubusercontent.com/659024/87855754-63c45300-c8e8-11ea-96b7-057db45867b7.jpg)

**Comment by molleweide** [comment] 2020-07-19 02:59
Dude this is interesting! I was nervous that it was I who had messed up reaper since I had installed huge amounts of scripts.

Again, tje bug serms to go away when you switch tab so I keep mult proj tabs open always

**Comment by elgiovanno** [comment] 2020-07-26 22:49
Just tried out 6.13, issue persists there. OSX 10.15.3

**Comment by molleweide** [comment] 2020-07-27 21:17
Should we file a bug report on the forum? I am not entirely sure what to write.

**Comment by gwatcha** [comment] 2020-08-07 10:43
hey guys! check out the latest release. i added a cool bindings list. type <SPC>b or <M-x> to show it. i also added seperate user configuration files so (starting from now), you're actions and bindings won't have conflicts when updating.

**Comment by gwatcha** [comment] 2020-08-07 19:15
im working on a better auto completion box now

**Comment by elgiovanno** [comment] 2020-08-07 23:47
> hey guys! check out the latest release. i added a cool bindings list. type <SPC>b or <M-x> to show it. i also added seperate user configuration files so (starting from now), you're actions and bindings won't have conflicts when updating.

🤯❤️ Checking it out tonight!

**Comment by molleweide** [comment] 2020-08-10 12:18
Holy shit Iam super excited about this. I havent hada lot of time lately. I’ll get back asap after having tried!!!!!!

**Comment by gwatcha** [comment] 2020-08-11 09:19
The completion box is pretty much done on the develop branch as well, check that out too! I'm wondering how good it works on other computers.

If you have any suggestions I'd love to hear before it gets merged into master.

**Comment by elgiovanno** [comment] 2020-08-14 02:53
I'll have a look at develop branch tomorrow!

**Comment by elgiovanno** [comment] 2020-08-14 02:55
> Dude this is interesting! I was nervous that it was I who had messed up reaper since I had installed huge amounts of scripts.
> 
> Again, tje bug serms to go away when you switch tab so I keep mult proj tabs open always

In regards to the issue, I found that clicking "clear" on the reaper keys console also resolves the issue. It's not a solution, but if you don't want to have to open another tab and switch from one to the other, I think that's maybe simpler.

**Comment by gwatcha** [comment] 2020-08-19 01:42
Alrighty! I finished the completions box. Check out the latest release guys. I'm curious about performance on other computers.

**Comment by elgiovanno** [comment] 2020-08-19 03:06
> Alrighty! I finished the completions box. Check out the latest release guys. I'm curious about performance on other computers.

Just pulled down this awesome looking release! everything is broken for me :/ OSX Catalina 10.5.3, REAPER 6.11-6.13.

I get the new reaper keys feedback dialog which looks awesome BTW, but only one command will run before the dialog stops responding to actions. Not sure at all what's going on yet though.o

**Comment by gwatcha** [comment] 2020-08-19 22:42
Ah, that sucks! I'll test it out on windows and see if a similar issue is there.

**Comment by gwatcha** [comment] 2020-08-19 23:10
It seems to work on window., I also pushed a new release that fixed a bug with the window opening very small there, it may be related to your issue.

**Comment by gwatcha** [comment] 2020-08-20 05:27
Try the 'resetfeedbackwindow' command as well through the binding list

**Comment by elgiovanno** [comment] 2020-08-20 14:26
I pulled the latest and there was an improvement, but the dialog is still becoming unresponsive after every command. To execute any sequence of commands I have to ESC out of the dialog in between every key press. I haven't messed with the user binding list portion of this update because I have a new machine without my code editor installed. I'm getting that setup as we speak and will try that out. What about the arrow keys??? not sure what you meant by that.

**Comment by elgiovanno** [comment] 2020-08-20 15:33
Tried resetting feedback window... did not help

**Comment by gwatcha** [comment] 2020-08-20 16:19
It sounds like there's an issue on Mac where when windows are resized, they are focused. When the feedback window is focused key presses don't work.

To confirm this, does it work if you click outside the window instead of pressing ESC between key presses? 
And there is an idle time before the completion window resizes to show completions, if you enter for example 'zz' quickly, does sit work?

**Comment by elgiovanno** [comment] 2020-08-20 16:44
Clicking out to unfocus the window does return fluidity between keypresses, although not completely. For example hitting space after unfocusing gives this dialog: ![PHOTO_20200820_124133.jpg](https://user-images.githubusercontent.com/659024/90800386-9811a180-e2e2-11ea-95b7-c923158570a2.jpg)

Closing the window and "starting over" with space brings us back to working but the window focused, unfocusing allows you to continue, with that exception. I also noticed I could not enter visual track mode but am unsure if it's for he same reason.

**Comment by gwatcha** [comment] 2020-08-20 17:02
Well I'm happy it turned out to just be a focusing issue! I think I may create a message on window creation to tell the user to unfocus the window to prevent this.

**Comment by elgiovanno** [comment] 2020-08-20 17:42
As an aside, the original issue for this thread continues on versions 6.12+

**Comment by elgiovanno** [comment] 2020-08-20 17:42
> Yeah that dialog is expected, just hit 'new instance'

Thanks!

**Comment by elgiovanno** [comment] 2020-08-20 17:42
> Well I'm happy it turned out to just be a focusing issue! I think I may create a message on window creation to tell the user to unfocus the window to prevent this.

Sounds good!

**Comment by molleweide** [comment] 2020-08-27 19:02
Yo I just wanted to chime in and tell you that I haven’t had much time to check out the latest version. However, the new github readme looks really great!!

**Comment by molleweide** [comment] 2020-08-28 08:03
Dude, the new gui looks amazing. I start laughing when I see it bc it feels so dope to have it.

**Comment by gwatcha** [comment] 2020-08-29 00:16
Thanks a lot for the support guys! If I didn't have all your guys' positive feedback I would not have had the motivation to make it :)

**Comment by molleweide** [comment] 2020-08-29 10:24
Awesome! Im gonna see if I can make some more time this week to dive deeper into it.

**Closed** 2020-09-20 03:11 UTC

**Comment by molleweide** [comment] 2020-10-24 14:55
n

> > Dude this is interesting! I was nervous that it was I who had messed up reaper since I had installed huge amounts of scripts.
> > Again, tje bug serms to go away when you switch tab so I keep mult proj tabs open always
>
> In regards to the issue, I found that clicking "clear" on the reaper keys console also resolves the issue. It's not a solution, but if you don't want to have to open another tab and switch from one to the other, I think that's maybe simpler.

1 This resolves issue quite fast: `1.) switch focus to RK Feedbackwindow and 2.) then switch back to main`

2. macOS cycle app windows shortcut !!!!!!!!!!!!!!!!

3. binding this to a non reaper key might work.

**Comment by molleweide** [comment] 2020-10-24 16:38
I fixed the issue in 91512dedcbf87a62b37583d7b260617eacab5f6b and it works really well!
