### ISSUE TITLE
Support Windows filenames

### ISSUE THREAD

**Issue by tmwitczak** [gwatcha/reaper-keys#3] opened 2020-05-26 12:59 UTC
### Description

The repository can't be cloned on Windows due to the use of the [reserved filename characters](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file): **<** and **>**.

### Context

- `git --version`
_git version 2.26.2.windows.1_

- `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`
_OS Name: Microsoft Windows 7 Ultimate
OS Version: 6.1.7601 Service Pack 1 Build 7601_

### Reproducing

- `git clone https://github.com/gwatcha/reaper-keys`
_Cloning into 'reaper-keys'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 4070 (delta 71), reused 91 (delta 48), pack-reused 3938
Receiving objects: 100% (4070/4070), 45.83 MiB | 10.30 MiB/s, done.
Resolving deltas: 100% (3557/3557), done._
***error: invalid path 'key_scripts/main_<.lua'***
_fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'_

### Possible solution

The reserved characters could be replaced with the ones supported on Windows, as stated [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file).

**Comment by jrbp** [comment] 2020-05-26 16:31
I'm also having this problem.  I've tried enabling extra characters using fsutil, but that still doesn't seem to work with the "<>" characters.

From a quick glance it looks like the characters can be dealt with by adding to ALIASES in scripts/key_definitions.rb.

However, the windows filesystem is not case sensitive so some files in key_scripts, for example C-a and C-A, will also need to be renamed.

**Comment by gwatcha** [comment] 2020-05-26 18:48
I've pushed a fix that makes the paths play nicer with windows, though I can't test it so I'm not sure I caught everything. 

Let me know if anything is still breaking, and if not I'll close this!

**Comment by jrbp** [comment] 2020-05-26 20:43
Now the filenames are okay and I can actually git clone and intsall in to reaper.

A new issue appears though. When I press any key I get the ReaScript :
`error main_SPC.lua:4: attempt to concatenate a nil value (local 'root_path')`
this is for any key SPC is just an example.

All the key_scripts files have lines 3 and 4
3 `local root_path = info.source:match[[[^@]*reaper.keys/]]`
4 `package.path = package.path .. ';' .. root_path .. '?.lua'`
 Maybe the problem is the trailing "/" since on Windows "\\" is used to separate directories?

**Comment by gwatcha** [comment] 2020-05-26 22:13
That's indeed the problem. I'll work on changing all the paths used throughout the library to be insensitive to this. I really should have tested this on windows!

**Comment by gwatcha** [comment] 2020-05-26 23:40
Alright I fixed the path names! I found a windows laptop to use as well and tested it out myself, so it should be good now.

**Comment by jrbp** [comment] 2020-05-27 10:24
Seems to be working now, well done!

**Comment by gwatcha** [comment] 2020-05-27 16:11
Cool! Thanks for helping me out.

**Closed by gwatcha** 2020-05-27 16:11 UTC
